#pragma once

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 200

// AUTO_SHIFT
#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_NUMERIC

// MOUSEKEY
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 32
// ホイールの加速無効
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define MOUSEKEY_WHEEL_MAX_SPEED 20
