MOUSEKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
AUDIO_ENABLE = no
UNICODE_ENABLE = yes
EXTRAFLAGS += -flto

RGB_MATRIX_ENABLE = no
OS_DETECTION_ENABLE = yes
COMBO_ENABLE = yes

# 最適化
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
